### ISSUE TITLE
node modules cache path

### ISSUE THREAD

**Issue by marcomorain** [CircleCI-Public/circleci-demo-javascript-express#1]
Hi @hannahhenderson 

I think there might be a typo on this line: https://github.com/CircleCI-Public/circleci-demo-javascript-express/blob/3daaeeffbb3b13643851537273cdd3c13b996203/.circleci/config.yml#L21

```
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
```

I think the path should be `node_modules` or `./node_modules`?
