### ISSUE TITLE
aws command not found

### ISSUE THREAD

**Issue by panppp119** [CircleCI-Public/circleci-demo-javascript-express#11]
Got an error 

> aws: command not found

Here is my code

```
steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install yarn
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install awscli
          command: |
            sudo apt-get install python-pip python-dev
            pip install 'pyyaml<4,>=3.10' awscli --upgrade --user

      - run:
          name: AWS S3
          command: aws s3 sync build s3://<URL>--delete
```
