### ISSUE TITLE
Setup test summary

### ISSUE THREAD

**Issue by zzak** [CircleCI-Public/circleci-demo-javascript-express#7]
Test summary isn't reporting on our demo project

/cc @smart-alek

**Comment by zzak** [comment]
Here's an example:

```
    steps:
      - checkout
      - run: npm install tap-junit
      - run: npm install
      - run: npm run test:ci | ./node_modules/tap-junit/bin/tap-junit --output test_results --name junit
      - store_artifacts:
          path: test_results
          prefix: test_results
      - store_test_results:
          path: test_results
```
